name: Cell generation

on: workflow_dispatch

jobs:
  cell-generation:
    name: cell generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Generate cell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./src
          python3 ./generate.py
          git config user.name 'cellspace Bot'
          git config user.email 'cellspace-bot@u-rth.com'
          git commit -am "add result $(date +%Y%m%d)"
          git push origin main

      - name: test # test to check if system ends generation
        run: |
          bash ./src/end_test.sh
        timeout-minutes: 5
