name: Dispatch test

on:
  repository_dispatch:
    types: [build]

jobs:
  dispatch_test:
    name: dispatch test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: run test
        run: |
          echo "run sucessfully"
