name: Scheduled cell generation

on:
  schedule:
    # runs on Monday 12:00(JST)
    # runs on Monday 03:00(UTC)
    - cron: '0 3 * * 1'

jobs:
  cell-generation:
    name: cell generation
    runs-on: ubuntu-latest
    steps:
      - name: generate
        run: ./src/generate.py
      - name: test # test to check if system ends generation
        run: ./src/end_test.sh
        timeout-minutes: 5
